version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: to-do-list-node
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine
    container_name: to-do-list-postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
